name: Pull Request Checker

on:
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Setup PNPM
              run: |
                npm i -g pnpm
                cd actions && pnpm i

            - name: Check
              run: make

            - name: Commit
              uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: "[skip ci] chore: update index"
                  push: true
